#!/usr/bin/env bash
#SBATCH -A NAISS2024-22-1123 -p alvis
#SBATCH -N 1 --gpus-per-node=A40:1
#SBATCH -t 0-20:00:00

module load Python/3.9.6-GCCcore-11.2.0;
source /cephyr/users/fracal/Alvis/UniMTS/SET_ENVIRONMENT_VARIABLES.sh;
source /mimer/NOBACKUP/groups/focs/virtualenvs/.unimts/bin/activate;

python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 1 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_1_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 2 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_2_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 3 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_3_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 4 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_4_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 5 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_5_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 6 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_6_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 7 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_7_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 8 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_8_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 9 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_9_Multisensor_Seed_1.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 10 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_10_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 11 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_11_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 12 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_12_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 13 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_13_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 14 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_14_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 15 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_15_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 16 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_16_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 17 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_17_Multisensor_Seed_1.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 18 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_18_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 19 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_19_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 20 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_20_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 21 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_21_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 22 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_22_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 23 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_23_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 24 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_24_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 25 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_25_Multisensor_Seed_1.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 26 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_26_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 27 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_27_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 28 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_28_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 29 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_29_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 30 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_30_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 31 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_31_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 32 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_32_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 33 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_33_Multisensor_Seed_1.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 34 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_34_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 35 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_35_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 36 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_36_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 37 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_37_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 38 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_38_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 39 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_39_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 40 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_40_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 41 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_41_Multisensor_Seed_1.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 42 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_42_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 43 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_43_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 44 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_44_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 45 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_45_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 46 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_46_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 47 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_47_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 48 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_48_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 49 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_49_Multisensor_Seed_1.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 50 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_50_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 1 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_1_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 2 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_2_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 3 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_3_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 4 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_4_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 5 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_5_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 6 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_6_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 7 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_7_Multisensor_Seed_2.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 8 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_8_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 9 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_9_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 10 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_10_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 11 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_11_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 12 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_12_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 13 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_13_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 14 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_14_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 15 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_15_Multisensor_Seed_2.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 16 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_16_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 17 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_17_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 18 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_18_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 19 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_19_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 20 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_20_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 21 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_21_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 22 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_22_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 23 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_23_Multisensor_Seed_2.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 24 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_24_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 25 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_25_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 26 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_26_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 27 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_27_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 28 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_28_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 29 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_29_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 30 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_30_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 31 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_31_Multisensor_Seed_2.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 32 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_32_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 33 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_33_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 34 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_34_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 35 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_35_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 36 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_36_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 37 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_37_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 38 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_38_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 39 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_39_Multisensor_Seed_2.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 40 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_40_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 41 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_41_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 42 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_42_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 43 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_43_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 44 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_44_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 45 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_45_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 46 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_46_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 47 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_47_Multisensor_Seed_2.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 48 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_48_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 49 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_49_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 50 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_50_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 1 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_1_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 2 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_2_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 3 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_3_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 4 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_4_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 5 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_5_Multisensor_Seed_3.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 6 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_6_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 7 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_7_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 8 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_8_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 9 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_9_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 10 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_10_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 11 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_11_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 12 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_12_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 13 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_13_Multisensor_Seed_3.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 14 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_14_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 15 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_15_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 16 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_16_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 17 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_17_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 18 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_18_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 19 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_19_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 20 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_20_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 21 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_21_Multisensor_Seed_3.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 22 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_22_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 23 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_23_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 24 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_24_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 25 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_25_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 26 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_26_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 27 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_27_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 28 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_28_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 29 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_29_Multisensor_Seed_3.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 30 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_30_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 31 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_31_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 32 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_32_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 33 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_33_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 34 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_34_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 35 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_35_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 36 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_36_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 37 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_37_Multisensor_Seed_3.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 38 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_38_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 39 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_39_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 40 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_40_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 41 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_41_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 42 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_42_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 43 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_43_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 44 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_44_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 45 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_45_Multisensor_Seed_3.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 46 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_46_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 47 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_47_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 48 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_48_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 49 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_49_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 50 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_50_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 1 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_1_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 2 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_2_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 3 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_3_Multisensor_Seed_4.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 4 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_4_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 5 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_5_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 6 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_6_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 7 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_7_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 8 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_8_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 9 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_9_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 10 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_10_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 11 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_11_Multisensor_Seed_4.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 12 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_12_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 13 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_13_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 14 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_14_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 15 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_15_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 16 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_16_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 17 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_17_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 18 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_18_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 19 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_19_Multisensor_Seed_4.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 20 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_20_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 21 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_21_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 22 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_22_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 23 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_23_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 24 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_24_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 25 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_25_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 26 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_26_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 27 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_27_Multisensor_Seed_4.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 28 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_28_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 29 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_29_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 30 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_30_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 31 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_31_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 32 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_32_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 33 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_33_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 34 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_34_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 35 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_35_Multisensor_Seed_4.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 36 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_36_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 37 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_37_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 38 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_38_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 39 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_39_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 40 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_40_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 41 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_41_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 42 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_42_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 43 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_43_Multisensor_Seed_4.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 44 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_44_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 45 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_45_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 46 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_46_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 47 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_47_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 48 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_48_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 49 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_49_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 50 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_50_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 1 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_1_Multisensor_Seed_5.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 2 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_2_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 3 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_3_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 4 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_4_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 5 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_5_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 6 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_6_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 7 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_7_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 8 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_8_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 9 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_9_Multisensor_Seed_5.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 10 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_10_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 11 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_11_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 12 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_12_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 13 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_13_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 14 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_14_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 15 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_15_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 16 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_16_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 17 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_17_Multisensor_Seed_5.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 18 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_18_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 19 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_19_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 20 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_20_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 21 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_21_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 22 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_22_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 23 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_23_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 24 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_24_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 25 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_25_Multisensor_Seed_5.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 26 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_26_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 27 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_27_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 28 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_28_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 29 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_29_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 30 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_30_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 31 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_31_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 32 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_32_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 33 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_33_Multisensor_Seed_5.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 34 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_34_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 35 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_35_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 36 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_36_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 37 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_37_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 38 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_38_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 39 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_39_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 40 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_40_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 41 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_41_Multisensor_Seed_5.log &
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 42 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_42_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 43 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_43_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 44 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_44_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 45 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_45_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 46 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_46_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 47 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_47_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 48 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_48_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 49 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_49_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset TNDAHAR --experiment 50 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/TNDAHAR_UNIMTS_50_Multisensor_Seed_5.log &
wait
