#!/usr/bin/env bash
#SBATCH -A NAISS2024-22-1123 -p alvis
#SBATCH -N 1 --gpus-per-node=A40:1
#SBATCH -t 0-20:00:00

module load Python/3.9.6-GCCcore-11.2.0;
source /cephyr/users/fracal/Alvis/UniMTS/SET_ENVIRONMENT_VARIABLES.sh;
source /mimer/NOBACKUP/groups/focs/virtualenvs/.unimts/bin/activate;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 1 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_1_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 2 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_2_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 3 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_3_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 4 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_4_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 5 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_5_RLA.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 6 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_6_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 7 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_7_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 8 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_8_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 9 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_9_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 10 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_10_RLA.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 11 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_11_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 12 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_12_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 13 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_13_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 14 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_14_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 15 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_15_RLA.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 16 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_16_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RLA --experiment 17 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_17_RLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 1 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_1_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 2 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_2_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 3 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_3_RUA.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 4 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_4_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 5 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_5_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 6 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_6_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 7 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_7_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 8 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_8_RUA.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 9 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_9_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 10 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_10_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 11 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_11_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 12 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_12_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 13 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_13_RUA.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 14 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_14_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 15 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_15_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 16 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_16_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RUA --experiment 17 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_17_RUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 1 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_1_LUA.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 2 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_2_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 3 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_3_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 4 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_4_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 5 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_5_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 6 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_6_LUA.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 7 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_7_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 8 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_8_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 9 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_9_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 10 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_10_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 11 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_11_LUA.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 12 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_12_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 13 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_13_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 14 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_14_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 15 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_15_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 16 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_16_LUA.log;
wait