#!/usr/bin/env bash
#SBATCH -A NAISS2024-22-1123 -p alvis
#SBATCH -N 1 --gpus-per-node=A40:1
#SBATCH -t 0-20:00:00

module load Python/3.9.6-GCCcore-11.2.0;
module load MATLAB/2023b
source /mimer/NOBACKUP/groups/focs/virtualenvs/.unimts/bin/activate;
source /cephyr/users/fracal/Alvis/UniMTS/SET_ENVIRONMENT_VARIABLES.sh;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 16 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_16_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 17 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_17_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 1 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_1_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 2 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_2_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 3 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_3_RC.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 4 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_4_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 5 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_5_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 6 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_6_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 7 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_7_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 8 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_8_RC.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 9 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_9_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 10 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_10_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 11 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_11_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 12 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_12_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 13 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_13_RC.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 14 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_14_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 15 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_15_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 16 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_16_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RC --experiment 17 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_17_RC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 1 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_1_RT.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 2 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_2_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 3 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_3_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 4 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_4_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 5 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_5_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 6 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_6_RT.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 7 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_7_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 8 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_8_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 9 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_9_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 10 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_10_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 11 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_11_RT.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 12 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_12_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 13 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_13_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 14 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_14_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 15 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_15_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 16 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_16_RT.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition RT --experiment 17 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_17_RT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 1 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_1_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 2 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_2_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 3 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_3_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 4 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_4_BACK.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 5 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_5_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 6 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_6_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 7 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_7_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 8 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_8_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 9 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_9_BACK.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 10 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_10_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 11 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_11_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 12 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_12_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 13 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_13_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 14 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_14_BACK.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 15 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_15_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 16 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_16_BACK.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition BACK --experiment 17 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_17_BACK.log &
wait