#!/usr/bin/env bash
#SBATCH -A NAISS2024-22-1123 -p alvis
#SBATCH -N 1 --gpus-per-node=A40:1
#SBATCH -t 0-20:00:00
module load Python/3.9.6-GCCcore-11.2.0;
source /cephyr/users/fracal/Alvis/UniMTS/SET_ENVIRONMENT_VARIABLES.sh;
source /mimer/NOBACKUP/groups/focs/virtualenvs/.unimts/bin/activate;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LUA --experiment 17 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_17_LUA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 1 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_1_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 2 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_2_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 3 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_3_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 4 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_4_LLA.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 5 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_5_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 6 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_6_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 7 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_7_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 8 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_8_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 9 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_9_LLA.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 10 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_10_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 11 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_11_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 12 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_12_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 13 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_13_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 14 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_14_LLA.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 15 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_15_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 16 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_16_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LLA --experiment 17 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_17_LLA.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 1 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_1_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 2 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_2_LT.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 3 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_3_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 4 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_4_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 5 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_5_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 6 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_6_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 7 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_7_LT.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 8 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_8_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 9 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_9_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 10 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_10_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 11 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_11_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 12 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_12_LT.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 13 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_13_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 14 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_14_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 15 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_15_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 16 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_16_LT.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LT --experiment 17 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_17_LT.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 1 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_1_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 2 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_2_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 3 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_3_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 4 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_4_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 5 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_5_LC.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 6 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_6_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 7 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_7_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 8 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_8_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 9 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_9_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 10 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_10_LC.log;
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 11 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_11_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 12 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_12_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 13 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_13_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 14 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_14_LC.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs --device cuda:0 --SensorPosition LC --experiment 15 >> /mimer/NOBACKUP/groups/focs/log/REALDISP_UNIMTS_15_LC.log;
wait