#!/usr/bin/env bash
#SBATCH -A NAISS2024-22-1123 -p alvis
#SBATCH -N 1 --gpus-per-node=A40:1
#SBATCH -t 0-20:00:00

module load Python/3.9.6-GCCcore-11.2.0;
source /cephyr/users/fracal/Alvis/UniMTS/SET_ENVIRONMENT_VARIABLES.sh;
source /mimer/NOBACKUP/groups/focs/virtualenvs/.unimts/bin/activate;


python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 1 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_1_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 2 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_2_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 3 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_3_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 4 --seed 1 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_4_Multisensor_Seed_1.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 1 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_1_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 2 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_2_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 3 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_3_Multisensor_Seed_2.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 4 --seed 2 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_4_Multisensor_Seed_2.log 
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 1 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_1_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 2 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_2_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 3 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_3_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 4 --seed 3 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_4_Multisensor_Seed_3.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 1 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_1_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 2 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_2_Multisensor_Seed_4.log 
wait
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 3 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_3_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 4 --seed 4 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_4_Multisensor_Seed_4.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 1 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_1_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 2 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_2_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 3 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_3_Multisensor_Seed_5.log &
python3 /cephyr/users/fracal/Alvis/UniMTS/finetune_1.py --mode full --batch_size 32 --num_epochs 200 --checkpoint './checkpoint/UniMTS.pth' --data_path /mimer/NOBACKUP/groups/focs/ --device cuda:0 --dataset OPPORTUNITY --experiment 4 --seed 5 >> /mimer/NOBACKUP/groups/focs/log/OPPORTUNITY_UNIMTS_4_Multisensor_Seed_5.log 
wait